---
title: 异常：invalidArg 函数 (F#)
description: '了解如何 F # invalidArg 函数生成参数异常。'
ms.date: 05/16/2016
ms.openlocfilehash: 43e1b6f3f36774ac50aeff147f75f133d6e3e5dc
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/04/2018
ms.locfileid: "33564503"
---
# <a name="exceptions-the-invalidarg-function"></a><span data-ttu-id="62385-103">异常：invalidArg 函数</span><span class="sxs-lookup"><span data-stu-id="62385-103">Exceptions: The invalidArg Function</span></span>

<span data-ttu-id="62385-104">`invalidArg`函数将生成自变量异常。</span><span class="sxs-lookup"><span data-stu-id="62385-104">The `invalidArg` function generates an argument exception.</span></span>


## <a name="syntax"></a><span data-ttu-id="62385-105">语法</span><span class="sxs-lookup"><span data-stu-id="62385-105">Syntax</span></span>

```fsharp
invalidArg parameter-name error-message-string
```

## <a name="remarks"></a><span data-ttu-id="62385-106">备注</span><span class="sxs-lookup"><span data-stu-id="62385-106">Remarks</span></span>
<span data-ttu-id="62385-107">在上述语法中的参数名称是参数的带有其自变量无效的名称的字符串。</span><span class="sxs-lookup"><span data-stu-id="62385-107">The parameter-name in the previous syntax is a string with the name of the parameter whose argument was invalid.</span></span> <span data-ttu-id="62385-108">*错误消息字符串*是一个文本字符串或类型的值`string`。</span><span class="sxs-lookup"><span data-stu-id="62385-108">The *error-message-string* is a literal string or a value of type `string`.</span></span> <span data-ttu-id="62385-109">它将成为`Message`异常对象的属性。</span><span class="sxs-lookup"><span data-stu-id="62385-109">It becomes the `Message` property of the exception object.</span></span>

<span data-ttu-id="62385-110">生成的异常`invalidArg`是`System.ArgumentException`异常。</span><span class="sxs-lookup"><span data-stu-id="62385-110">The exception generated by `invalidArg` is a `System.ArgumentException` exception.</span></span> <span data-ttu-id="62385-111">下面的代码演示如何使用`invalidArg`引发异常。</span><span class="sxs-lookup"><span data-stu-id="62385-111">The following code illustrates the use of `invalidArg` to throw an exception.</span></span>

[!code-fsharp[Main](../../../../samples/snippets/fsharp/lang-ref-2/snippet6101.fs)]

<span data-ttu-id="62385-112">输出为以下内容，然后由堆栈跟踪 （未显示）。</span><span class="sxs-lookup"><span data-stu-id="62385-112">The output is the following, followed by a stack trace (not shown).</span></span>

```
December
January
System.ArgumentException: Month parameter out of range.
```

## <a name="see-also"></a><span data-ttu-id="62385-113">请参阅</span><span class="sxs-lookup"><span data-stu-id="62385-113">See Also</span></span>
[<span data-ttu-id="62385-114">异常处理</span><span class="sxs-lookup"><span data-stu-id="62385-114">Exception Handling</span></span>](index.md)

[<span data-ttu-id="62385-115">异常类型</span><span class="sxs-lookup"><span data-stu-id="62385-115">Exception Types</span></span>](exception-types.md)

[<span data-ttu-id="62385-116">异常：`try...with` 表达式</span><span class="sxs-lookup"><span data-stu-id="62385-116">Exceptions: The `try...with` Expression</span></span>](the-try-with-expression.md)

[<span data-ttu-id="62385-117">异常：`try...finally` 表达式</span><span class="sxs-lookup"><span data-stu-id="62385-117">Exceptions: The `try...finally` Expression</span></span>](the-try-finally-expression.md)

[<span data-ttu-id="62385-118">异常：`raise` 函数</span><span class="sxs-lookup"><span data-stu-id="62385-118">Exceptions: the `raise` Function</span></span>](the-raise-function.md)

[<span data-ttu-id="62385-119">异常：`failwith` 函数</span><span class="sxs-lookup"><span data-stu-id="62385-119">Exceptions: The `failwith` Function</span></span>](the-failwith-function.md)
