---
title: "编译器错误 CS1626"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-csharp
ms.topic: article
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
caps.latest.revision: 
author: BillWagner
ms.author: wiwagn
ms.openlocfilehash: 7e991faee8fcd6b8bfbfbbcf77ce243e652a008f
ms.sourcegitcommit: 83dd5ec003e788ccb3e33f3412a7af39ae347646
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 03/15/2018
---
# <a name="compiler-error-cs1626"></a>编译器错误 CS1626
无法在包含 catch 子句的 Try 块体中生成值  
  
 如果有一个 catch 子句与 try 块关联，该 try 块内不允许有 yield 语句。 若要避免此错误，请将 yield 语句移到 catch 子句的外部。  
  
 下面的示例生成 CS1626：  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
