---
title: 编译器错误 CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 3d24280006d77c807109723cd05d2836570fdc91
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/04/2018
ms.locfileid: "33308202"
---
# <a name="compiler-error-cs1626"></a><span data-ttu-id="9971e-102">编译器错误 CS1626</span><span class="sxs-lookup"><span data-stu-id="9971e-102">Compiler Error CS1626</span></span>
<span data-ttu-id="9971e-103">无法在包含 catch 子句的 Try 块体中生成值</span><span class="sxs-lookup"><span data-stu-id="9971e-103">Cannot yield a value in the body of a try block with a catch clause</span></span>  
  
 <span data-ttu-id="9971e-104">如果有一个 catch 子句与 try 块关联，该 try 块内不允许有 yield 语句。</span><span class="sxs-lookup"><span data-stu-id="9971e-104">A yield statement is not allowed in a try block if there is a catch clause associated with the try block.</span></span> <span data-ttu-id="9971e-105">若要避免此错误，请将 yield 语句移到 catch 子句的外部。</span><span class="sxs-lookup"><span data-stu-id="9971e-105">To avoid this error, move the yield statement out of the catch clause.</span></span>  
  
 <span data-ttu-id="9971e-106">下面的示例生成 CS1626：</span><span class="sxs-lookup"><span data-stu-id="9971e-106">The following sample generates CS1626:</span></span>  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
