---
title: 编译器错误 CS1626
ms.date: 07/20/2015
f1_keywords:
- CS1626
helpviewer_keywords:
- CS1626
ms.assetid: 3ba03383-eb24-4fd8-bf40-8b0f7d6baf0d
ms.openlocfilehash: 3d24280006d77c807109723cd05d2836570fdc91
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/04/2018
ms.locfileid: "33308202"
---
# <a name="compiler-error-cs1626"></a>编译器错误 CS1626
无法在包含 catch 子句的 Try 块体中生成值  
  
 如果有一个 catch 子句与 try 块关联，该 try 块内不允许有 yield 语句。 若要避免此错误，请将 yield 语句移到 catch 子句的外部。  
  
 下面的示例生成 CS1626：  
  
```csharp  
// CS1626.cs  
using System.Collections;  
  
class C : IEnumerable  
{  
   public IEnumerator GetEnumerator()  
   {  
      try  
      {  
         yield return this;  // CS1626  
      }  
      catch  
      {  
  
      }  
   }  
}  
  
public class CMain  
{  
   public static void Main() { }  
}  
```
