---
title: '&#39;捕获&#39;后不能出现&#39;最后&#39;内&#39;重&#39;语句'
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: f0eec8db52d71fb61a85a2811f4904c4ad745b67
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/04/2018
ms.locfileid: "33611445"
---
# <a name="39catch39-cannot-appear-after-39finally39-within-a-39try39-statement"></a>&#39;捕获&#39;后不能出现&#39;最后&#39;内&#39;重&#39;语句
`Catch` 语句出现在代码中结束 `Finally` 语句块的 `Try` 之后。 `Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。  
  
 **错误 ID：** BC30379  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1.  将 `Catch` 语句移到代码中更合适的位置。  
  
## <a name="see-also"></a>请参阅  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
