---
title: "&#39;Catch &#39;无法显示在外部 &#39;请尝试 &#39;语句"
ms.date: 07/20/2015
ms.prod: .net
ms.technology:
- devlang-visual-basic
ms.topic: article
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
caps.latest.revision: 
author: dotnet-bot
ms.author: dotnetcontent
ms.openlocfilehash: defb7563950828014cb4a8293fe6e70d4777ee72
ms.sourcegitcommit: 34ec7753acf76f90a0fa845235ef06663dc9e36e
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/21/2017
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39;Catch &#39;无法显示在外部 &#39;请尝试 &#39;语句
`Catch` 必须出现在 `Try...Catch...Finally` 语句块之内。 或是 `Catch` 块中具有不必要的 `Try` ，或是 `Catch` 语句出现在其对应 `Try` 块的边界之外。  
  
 **错误 ID：** BC30380  
  
## <a name="to-correct-this-error"></a>更正此错误  
  
1.  如果 `Catch` 语句不必要，请删除它，或者请将其置于 `Try...Catch...Finally` 语句块之内。  
  
## <a name="see-also"></a>请参阅  
 [Try...Catch...Finally 语句](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
