---
title: 3303 - ReceiveContextAbandonWithException
ms.custom: 
ms.date: 03/30/2017
ms.prod: .net-framework
ms.reviewer: 
ms.suite: 
ms.technology: dotnet-clr
ms.tgt_pltfrm: 
ms.topic: article
ms.assetid: eae255f8-13fd-4d8e-9f9e-56aea0d588c3
caps.latest.revision: "3"
author: dotnet-bot
ms.author: dotnetcontent
manager: wpickett
ms.openlocfilehash: 91fcbc8d71446d23c41efd25a9f88a60c3db11bb
ms.sourcegitcommit: ce279f2d7fe2220e6ea0a25a8a7a5370ddf8d9f0
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/02/2017
---
# <a name="3303---receivecontextabandonwithexception"></a><span data-ttu-id="cf5d6-102">3303 - ReceiveContextAbandonWithException</span><span class="sxs-lookup"><span data-stu-id="cf5d6-102">3303 - ReceiveContextAbandonWithException</span></span>
## <a name="properties"></a><span data-ttu-id="cf5d6-103">属性</span><span class="sxs-lookup"><span data-stu-id="cf5d6-103">Properties</span></span>  
  
|||  
|-|-|  
|<span data-ttu-id="cf5d6-104">ID</span><span class="sxs-lookup"><span data-stu-id="cf5d6-104">ID</span></span>|<span data-ttu-id="cf5d6-105">3303</span><span class="sxs-lookup"><span data-stu-id="cf5d6-105">3303</span></span>|  
|<span data-ttu-id="cf5d6-106">关键字</span><span class="sxs-lookup"><span data-stu-id="cf5d6-106">Keywords</span></span>|<span data-ttu-id="cf5d6-107">通道</span><span class="sxs-lookup"><span data-stu-id="cf5d6-107">Channel</span></span>|  
|<span data-ttu-id="cf5d6-108">级别</span><span class="sxs-lookup"><span data-stu-id="cf5d6-108">Level</span></span>|<span data-ttu-id="cf5d6-109">信息</span><span class="sxs-lookup"><span data-stu-id="cf5d6-109">Information</span></span>|  
|<span data-ttu-id="cf5d6-110">通道</span><span class="sxs-lookup"><span data-stu-id="cf5d6-110">Channel</span></span>|<span data-ttu-id="cf5d6-111">Microsoft-Windows-应用程序服务器-应用程序/调试</span><span class="sxs-lookup"><span data-stu-id="cf5d6-111">Microsoft-Windows-Application Server-Applications/Debug</span></span>|  
  
## <a name="description"></a><span data-ttu-id="cf5d6-112">描述</span><span class="sxs-lookup"><span data-stu-id="cf5d6-112">Description</span></span>  
 <span data-ttu-id="cf5d6-113">当接收上下文放弃失败并且具有异常时，将发出此事件。</span><span class="sxs-lookup"><span data-stu-id="cf5d6-113">This event is emitted when the receive context abandon failed with an exception.</span></span>  
  
## <a name="message"></a><span data-ttu-id="cf5d6-114">消息</span><span class="sxs-lookup"><span data-stu-id="cf5d6-114">Message</span></span>  
 <span data-ttu-id="cf5d6-115">%1 被放弃并且具有异常 %2。</span><span class="sxs-lookup"><span data-stu-id="cf5d6-115">%1 was Abandoned with exception %2.</span></span>  
  
## <a name="details"></a><span data-ttu-id="cf5d6-116">详细信息</span><span class="sxs-lookup"><span data-stu-id="cf5d6-116">Details</span></span>
