---
title: 3303 - ReceiveContextAbandonWithException
ms.custom: 
ms.date: 03/30/2017
ms.prod: .net-framework
ms.reviewer: 
ms.suite: 
ms.technology: dotnet-clr
ms.tgt_pltfrm: 
ms.topic: article
ms.assetid: eae255f8-13fd-4d8e-9f9e-56aea0d588c3
caps.latest.revision: "3"
author: dotnet-bot
ms.author: dotnetcontent
manager: wpickett
ms.openlocfilehash: 91fcbc8d71446d23c41efd25a9f88a60c3db11bb
ms.sourcegitcommit: ce279f2d7fe2220e6ea0a25a8a7a5370ddf8d9f0
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 12/02/2017
---
# <a name="3303---receivecontextabandonwithexception"></a>3303 - ReceiveContextAbandonWithException
## <a name="properties"></a>属性  
  
|||  
|-|-|  
|ID|3303|  
|关键字|通道|  
|级别|信息|  
|通道|Microsoft-Windows-应用程序服务器-应用程序/调试|  
  
## <a name="description"></a>描述  
 当接收上下文放弃失败并且具有异常时，将发出此事件。  
  
## <a name="message"></a>消息  
 %1 被放弃并且具有异常 %2。  
  
## <a name="details"></a>详细信息
